repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: true
  default_branch: main
  delete_branch_on_merge: true
  description: The Hive - The secretly open NixOS-Society
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: true
  name: nix-dots
  private: false
