keys:
  - &aniket bdef09375e39dea3e1deb2976d90062cbe988b66
  - &andromeda a09192f027cefdb180fd17cba20a92d668313db4
creation_rules:
  - path_regex: secrets/sops/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *aniket
          - *andromeda
