keys:
  - &aniket bdef09375e39dea3e1deb2976d90062cbe988b66
  - &andromeda a09192f027cefdb180fd17cba20a92d668313db4
  - &horologium daca14f2518b4ea3899fc1131d202afcaa8b230d
  - &miranda 40bb7e16213cff0301fdfa26561abc217ba2418d
creation_rules:
  - path_regex: secrets/sops/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *aniket
          - *andromeda
          - *horologium
          - *miranda
