# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "eb00c13d7c9f937732305d47af5b8ccf895e700f";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "eb00c13d7c9f937732305d47af5b8ccf895e700f";
      fetchSubmodules = false;
      sha256 = "sha256-p0/inkHPRUkxSIsTmj7VI7sIaX7OXdqjMGZ31W7cnt4=";
    };
    date = "2024-04-18";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "414a7383464b98f21f5e5381a16cc73ae0350ba6";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "414a7383464b98f21f5e5381a16cc73ae0350ba6";
      fetchSubmodules = false;
      sha256 = "sha256-uoewZMGf3vsBoRDfRz8KBKl+J6st/J44SHvNRMBdaUI=";
    };
    date = "2024-04-18";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "8b51ca9c8b0ac4639556e3704216ba5b42231058";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "8b51ca9c8b0ac4639556e3704216ba5b42231058";
      fetchSubmodules = false;
      sha256 = "sha256-YWIcGXG66VaXgWXtNlMzS/ShZzE8vh5ePwbYyLbtPcM=";
    };
    date = "2024-04-29";
  };
}
