# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "5ff5efbdc35dc61873b950326ca6798c44a37686";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "5ff5efbdc35dc61873b950326ca6798c44a37686";
      fetchSubmodules = false;
      sha256 = "sha256-lKeTKTbrUWhzrEUMDGZO94w5AKAF8x6kUTYFa3hBTFM=";
    };
    date = "2023-10-05";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "7dfea8885ceebc714f9ea018d101963712ac60b9";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "7dfea8885ceebc714f9ea018d101963712ac60b9";
      fetchSubmodules = false;
      sha256 = "sha256-LZkGXbVxfYpe4Oom6LkVtO4SKuiK7e9dv+B1FzTr2Bs=";
    };
    date = "2023-10-10";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "b220c8c02000f6074c57c4ea68f686d8498245a9";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "b220c8c02000f6074c57c4ea68f686d8498245a9";
      fetchSubmodules = false;
      sha256 = "sha256-5T4LF+UxMvWG07GCDmt/Jgi5gVb2pG4CjJAIkDCe6fk=";
    };
    date = "2023-10-11";
  };
}
