# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "eb00c13d7c9f937732305d47af5b8ccf895e700f";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "eb00c13d7c9f937732305d47af5b8ccf895e700f";
      fetchSubmodules = false;
      sha256 = "sha256-p0/inkHPRUkxSIsTmj7VI7sIaX7OXdqjMGZ31W7cnt4=";
    };
    date = "2024-04-18";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "414a7383464b98f21f5e5381a16cc73ae0350ba6";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "414a7383464b98f21f5e5381a16cc73ae0350ba6";
      fetchSubmodules = false;
      sha256 = "sha256-uoewZMGf3vsBoRDfRz8KBKl+J6st/J44SHvNRMBdaUI=";
    };
    date = "2024-04-18";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "5d749064147c97d616ae5ae866d9a498c4ccfa6d";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "5d749064147c97d616ae5ae866d9a498c4ccfa6d";
      fetchSubmodules = false;
      sha256 = "sha256-/jry00g7bLq3VBR4sS/389wP8a7NLfV5WiyYUPcIZ0Q=";
    };
    date = "2024-04-24";
  };
}
