name: Build Andromeda
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-x86-host.yaml
    with:
      configuration: nixos-andromeda
    secrets: inherit